### ISSUE TITLE
Text2BeanConverter() raises a ClassNotFoundException in quarkus:dev mode

### ISSUE THREAD

**Issue by fsantagostinobietti** [org-tigris-jsapar/jsapar#14]
I'm using org.jsapar.**Text2BeanConverter**() in my java quarkus project.
When running it in **development mode** (i.e. `mvn quarkus:dev`) it raises a **ClassNotFoundException** trying lo load my custom bean.

Stack trace is:

```
org.jsapar.error.BeanException: Failed to create bean mapping based on schema - eu.examples.model.MyBean
        at org.jsapar.parse.bean.BeanPropertyMap.ofSchemaLine(BeanPropertyMap.java:79)
        at org.jsapar.bean.BeanMap.ofSchema(BeanMap.java:87)
        at org.jsapar.Text2BeanConverter.<init>(Text2BeanConverter.java:75)
        ...
Caused by: java.lang.ClassNotFoundException: eu.examples.model.MyBean
        at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:489)
        at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:466)
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:391)
        at java.base/java.lang.Class.forName(Class.java:382)
        at org.jsapar.parse.bean.BeanPropertyMap.ofPropertyNames(BeanPropertyMap.java:88)
        at org.jsapar.parse.bean.BeanPropertyMap.ofSchemaLine(BeanPropertyMap.java:77)
        ...
```
and this is the way I use jsapar converter:

```java
InputStream stream = getClass().getResourceAsStream("/my_schema.xml");
Schema schema = Schema.ofXml(new InputStreamReader(stream));

Text2BeanConverter<MyBean> converter = new Text2BeanConverter<MyBean>(schema);
converter.convertForEach( new StringReader(text), bean->{
    // do something with bean
});
```
**Note**: that it is working correctly when quarkus app is executed in **prod mode** (i.e. default) as `java -jar target/quarkus-app/quarkus-run.jar`.

Actual components versions:
* jsapar: 2.3.3
* quarkus: 3.2.0.Final
* jdk: openjdk 20.0.2
* OS: macos 13.6

**Comment by fsantagostinobietti** [comment]
It looks like it's related to the way quarkus uses classloader in dev mode.

[Here](https://github.com/quarkusio/quarkus/issues/2809) a hint on how to make 3rd-party libs "compatible" with quarkus:dev mode.

**Comment by stenix71** [comment]
Merged pull request. Closing issue.
